# Site settings
title:          DK-Lite
description:    "Machine Learning"
baseurl:        
url:            "https://dk-lite.github.io"

# Author
author:
  name:         Dokgo.kim
  url:          https://chester.how
  email:        kdk5go@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
